### ISSUE TITLE
can we pass user name in uri

### ISSUE THREAD

**Issue by dipenpatel235** [Tug/express-chat#5]
hello...
i can i pass my login user name to your plugin?
if yes so how?
because currently it is automatic fetch "Anonymous" user and then i need to rename that...
so if possible so give me some hep....

Thanks,
Dipen

**Comment by Tug** [comment]
Hi Dipen,
express-chat is not a plugin, it's a demo of a chat application.
That said, you will probably have to modify the 'join room' event to send a custom username from the client https://github.com/Tug/express-chat/blob/master/public/js/socket.chat.js#L16
You could have

```
client.emit('join room', {
    roomid: app.ROOMID,
    messageCount: app.msgCount,
    username: user.name,
}, function(err, name) {
    ...
```

Then you need to edit the code on the server side to use this username if present.
Hope it helps
